config/routes.rb
Rails.application.routes.draw do
  root 'topics#index'
  resources :topics
end

app/models/topic.rb
class Topic < ActiveRecord::Base
  validates :content, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController

  before_action :set_topic, only: [:show, :edit, :update, :destroy]

  def index
    @topic = Topic.new
    @topics = Topic.order("created_at DESC")
  end

  def new
    @topic = Topic.new
  end

  def create
    @topic = Topic.new(topics_params)
    if @topic.save
      redirect_to action: :index
    else
      redirect_to action: :index
    end
  end

  def show
    
  end

  def edit
    #code
  end


 def update
    if @topic.update(topics_params)
    redirect_to topics_path
    else
      render 'edit'
    end
 end


  def destroy
    @topic.destroy
    redirect_to topics_path
  end

  private
  def topics_params
    params.require(:topic).permit(:content)
  end

  def set_topic
    @topic = Topic.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Facebook</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/topics/edit.html.erb
<%= form_for @topic do |f| %>
  <%= f.text_field :content, placeholder: "今なにしてる？" %>
  <%= f.submit "編集する" %>
<% end %>

app/views/topics/index.html.erb
aaaa

<%= form_for @topic do |f| %>
  <%= f.text_field :content, placeholder: "今なにしてる？" %>
  <%= f.submit "投稿する" %>
<% end %>

<% @topics.each do |topic| %>
  <p>
    <%= topic.content %>
    <%= link_to "詳細", topic_path(topic.id) %>
    <%= link_to "編集", edit_topic_path(topic.id) %>
    <%= link_to "削除", topic_path(topic.id), method: :delete, data: {confirm: "削除しますか？"} %>
  </p>

<% end %>

app/views/topics/show.html.erb
<h1><%= @topic.content %></h1>